"""Tests for envlens.templater."""
from __future__ import annotations

from pathlib import Path

import pytest

from envlens.templater import (
    TemplateResult,
    generate_template,
    render_template,
    save_template,
)


@pytest.fixture()
def tmp_env(tmp_path: Path):
    return tmp_path


def _write(p: Path, content: str) -> Path:
    p.write_text(content, encoding="utf-8")
    return p


def test_generate_template_returns_keys(tmp_env):
    src = _write(tmp_env / ".env", "DB_HOST=localhost\nDB_PORT=5432\n")
    result = generate_template(src)
    assert isinstance(result, TemplateResult)
    assert result.keys == ["DB_HOST", "DB_PORT"]


def test_generate_template_source_path(tmp_env):
    src = _write(tmp_env / ".env", "KEY=value\n")
    result = generate_template(src)
    assert result.source_path == str(src)


def test_generate_template_no_output_by_default(tmp_env):
    src = _write(tmp_env / ".env", "KEY=value\n")
    result = generate_template(src)
    assert result.output_path is None


def test_render_template_strips_values(tmp_env):
    src = _write(tmp_env / ".env", "SECRET=supersecret\nAPI_KEY=abc123\n")
    rendered = render_template(src)
    assert "SECRET=" in rendered
    assert "supersecret" not in rendered
    assert "API_KEY=" in rendered
    assert "abc123" not in rendered


def test_render_template_uses_placeholder(tmp_env):
    src = _write(tmp_env / ".env", "TOKEN=mytoken\n")
    rendered = render_template(src, placeholder="<CHANGE_ME>")
    assert "TOKEN=<CHANGE_ME>" in rendered


def test_render_template_includes_header_comment(tmp_env):
    src = _write(tmp_env / ".env", "FOO=bar\n")
    rendered = render_template(src, include_comments=True)
    assert rendered.startswith("# Generated by envlens")


def test_render_template_no_header_comment(tmp_env):
    src = _write(tmp_env / ".env", "FOO=bar\n")
    rendered = render_template(src, include_comments=False)
    assert not rendered.startswith("#")


def test_render_template_ends_with_newline(tmp_env):
    src = _write(tmp_env / ".env", "A=1\nB=2\n")
    rendered = render_template(src)
    assert rendered.endswith("\n")


def test_save_template_writes_file(tmp_env):
    src = _write(tmp_env / ".env", "DB=postgres\n")
    out = tmp_env / ".env.example"
    result = save_template(src, out)
    assert out.exists()
    assert result.output_path == str(out)


def test_save_template_content_has_no_original_values(tmp_env):
    src = _write(tmp_env / ".env", "PASSWORD=hunter2\n")
    out = tmp_env / ".env.example"
    save_template(src, out)
    content = out.read_text(encoding="utf-8")
    assert "hunter2" not in content
    assert "PASSWORD=" in content
