"""Generate .env.example / template files from existing .env files."""
from __future__ import annotations

from dataclasses import dataclass, field
from pathlib import Path
from typing import Dict, List, Optional

from envlens.parser import parse_env_file


@dataclass
class TemplateResult:
    """Result of a template generation operation."""
    source_path: str
    keys: List[str] = field(default_factory=list)
    output_path: Optional[str] = None

    def __repr__(self) -> str:  # pragma: no cover
        return (
            f"TemplateResult(source={self.source_path!r}, "
            f"keys={len(self.keys)}, output={self.output_path!r})"
        )


def _placeholder(key: str, placeholder: str) -> str:
    """Return a single KEY=<placeholder> line."""
    return f"{key}={placeholder}"


def generate_template(
    source: str | Path,
    placeholder: str = "",
    include_comments: bool = True,
) -> TemplateResult:
    """Read *source* and return a TemplateResult with values stripped.

    Args:
        source: Path to the .env file to use as the basis.
        placeholder: Value to substitute for every variable (default: empty).
        include_comments: Prepend a header comment when True.
    """
    path = Path(source)
    env: Dict[str, str] = parse_env_file(str(path))
    keys = list(env.keys())
    return TemplateResult(source_path=str(path), keys=keys)


def render_template(
    source: str | Path,
    placeholder: str = "",
    include_comments: bool = True,
) -> str:
    """Return the template as a string ready to be written to disk."""
    path = Path(source)
    env: Dict[str, str] = parse_env_file(str(path))
    lines: List[str] = []
    if include_comments:
        lines.append(f"# Generated by envlens from {path.name}")
        lines.append("# Fill in the values before use.")
        lines.append("")
    for key in env:
        lines.append(_placeholder(key, placeholder))
    return "\n".join(lines) + "\n"


def save_template(
    source: str | Path,
    output: str | Path,
    placeholder: str = "",
    include_comments: bool = True,
) -> TemplateResult:
    """Write the generated template to *output* and return a TemplateResult."""
    content = render_template(source, placeholder=placeholder, include_comments=include_comments)
    out_path = Path(output)
    out_path.write_text(content, encoding="utf-8")
    result = generate_template(source, placeholder=placeholder)
    result.output_path = str(out_path)
    return result
